### ISSUE TITLE
possible collaboration

### ISSUE THREAD

**Issue by edennis** [x-ji/kraken_api#1]
Hello there @x-ji! I noticed we've both been working on elixir clients for the Kraken API. I just wanted to reach out in case you might be interested in collaborating efforts. I've implemented all the API calls for "public market data", "private user data" and "private user trading." I still need to tackle "private user funding."

Here's the code if you're interested in trying it out: https://github.com/edennis/krakex. It's also available on hex: https://hex.pm/packages/krakex

I've designed it so that it can be used with multiple API keys. I'm happy to hear any feedback you might have! :)

**Comment by x-ji** [comment]
Thanks for your comment. I wrote that library as I wanted to do some automated trading, but I've been really busy recently and I feel I might not need it for now. If you are interested in taking a look at the code and using parts of it feel free to do so. It was quite hastily written though so I think your implementation might be better. Glad to see that somebody else is also taking up the task. You may also want to contact the Kraken team to get the library listed on their website. I will surely give you feedback when I find time again to build an Elixir app to interact with Kraken :)
